  - name: copy catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo 

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present 

  - name: get the entries count
    ansible.builtin.command: mongo --host mongodb.cbpdevops.store --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: entries_count
    when: component == "catalogue"

  - name: get the entries count
    ansible.builtin.command:  mongo --host mongodb.cbpdevops.store --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: entries_count
    when: component == "user"  

  #- name: print the count
   # ansible.builtin.debug:
    #  msg: "product count: {{product_count}}" 

  - name: "load {{component}} data"
    ansible.builtin.command: "mongo --host mongodb.cbpdevops.store < /app/schema/{{component}}.js"
    when: entries_count.stdout == "0"

  