- name: "copy {{componet}} service"
  ansible.builtin.copy:
    src: "{{componet}}.service"
    dest: "/etc/systemd/system/{{componet}}.service"

- name: deamon reload and start
  ansible.builtin.systemd_service:
    daemon_reload: true    

- name: "start and enable {{componet}}"
  ansible.builtin.service:
    name: "{{componet}}"
    state: restarted
    enabled: yes  

         